[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "CI-CD_dummy"
description = "Dummy CI/CD Pipeline"
requires-python = ">=3.8"
version = "0.1.0"
readme = { file = "README.md", content-type = "text/markdown" }